name = "Jar"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"
defaultContentLanguage = "en"

[author]
  name = "coleenhuang"
  homepage = "coleenhuang.com"

[languages]
  [languages.en]
    weight: 1
  [languages.zh]
    weight: 2


[params]
subtitle = "But I still want more"
mainSections = ["posts"]